name: Add License

on:
  push:
    branches: [ main ]

jobs:

  add-license:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 # Required to retrieve full commit history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Add License
      run: |
        python scripts/add_license.py
        
    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add --all
        git commit -m "Add license to files" || echo "No changes to commit"
        git push origin HEAD:main
