name: Add License

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  add-license:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Add License
      run: |
        python scripts/add_license.py
