name: Add License

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  add-license:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 # Required to retrieve full commit history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Add License
      run: |
        python scripts/add_license.py

    - name: Check for file changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi
        
    - name: Commit changes
      if: steps.changes.outputs.changes == true
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Add license to files"
        git push
