name: Add License

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  add-license:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 # Required to retrieve full commit history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Add License
      run: |
        output=$(python scripts/add_license.py) || ""
        echo "$output"
        if echo "$output" | grep -q "added"; then
          echo "added_license=true" >> $GITHUB_OUTPUT
        else
          echo "added_license=false" >> $GITHUB_OUTPUT
        fi
      id: add_license
        
    - name: Commit changes
      if: steps.add_license.outputs.added_license == true
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add --all
        git commit -m "Add license to files"
        git push
