name: Add License

on:
  push:
    branches: [ main ]

jobs:

  add-license:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 # Required to retrieve full commit history
          persist-credentials: false # Required to allow the use of the token to push back to the repository
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.10"
        
    - name: Add License
      run: |
        python scripts/add_license.py

    - uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
          email: "actions@github.com"
          name: "GitHub Actions Bot"
          commit_message: "Add license to files"
          target_branch: main
